from pathlib import Path
import json,hashlib,subprocess,re,datetime,os
P=Path(__file__).resolve().parent;D=Path('/Users/ah/GitHub/hybridclr/assembly_shadow_h1r/hybridclr_demo');C=Path(json.loads((P/'CHECKPOINT_LOCATION.json').read_text())['path']);rel=str(C.relative_to(D));docs=['Docs/AssemblyShadow/Handoff/LOCAL_VALIDATION.md','Docs/AssemblyShadow/Handoff/RETURN_TO_WEB.md'];PIN='ba57a3391da9627e694ee33f8bfe3cb993e6c56a'
def sha(p):
 with Path(p).open('rb') as f:return hashlib.file_digest(f,'sha256').hexdigest()
def git(*args):return subprocess.check_output(['git','-C',str(D),*args])
assert git('rev-parse','HEAD').decode().strip()==PIN;assert not git('diff','--cached','--name-only');changed=git('diff','--name-only').decode().splitlines();assert set(changed)==set(docs);status=git('status','--short','--untracked-files=all').decode();assert all(line[3:] in docs or line[3:].startswith(rel+'/') for line in status.splitlines())
history=json.loads((C/'REPORT_HISTORY_PRESERVATION.json').read_text())
for row in history['reports']:
 current=(D/row['file']).read_text();body='## Historical '+current.split('## Historical ',1)[1];assert hashlib.sha256(body.encode()).hexdigest()==row['historicalBodySha256'];row['currentFileSha256']=sha(D/row['file'])
(C/'REPORT_HISTORY_PRESERVATION.json').write_text(json.dumps(history,indent=2)+'\n')
links=[]
for p in [*[D/n for n in docs],C/'README.md']:
 text=p.read_text().split('## Historical ',1)[0]
 for t in re.findall(r'\[[^\]]*\]\(([^)]+)\)',text):
  if '://' in t or t.startswith('#'):continue
  target=t.strip('<>').split('#')[0];assert (p.parent/target).exists(),(p,target);links.append({'file':str(p.relative_to(D)),'target':target})
trans=json.loads((C/'FILE_TRANSPORT.json').read_text());opaque=[]
for row in trans['files']:
 whole=hashlib.sha256();total=0
 for part in row['parts']:
  p=C/part['path'];assert sha(p)==part['sha256'] and p.stat().st_size==part['size'];opaque.append(part['path'])
  with p.open('rb') as f:
   for b in iter(lambda:f.read(1048576),b''):whole.update(b);total+=len(b)
 assert whole.hexdigest()==row['originalSha256']==sha(row['originalLivePath']) and total==row['originalSize']
source=json.loads((C/'SOURCE_BINDINGS.json').read_text())
for row in source['files']:assert sha(C/row['snapshot'])==row['sha256'] and hashlib.sha256(subprocess.check_output(['git','-C',row['repositoryPath'],'show',row['commit']+':'+row['path']])).hexdigest()==row['sha256']
# Raw generated bytes have intentional native whitespace. Owned report prose stays checked.
attrs=['# Preserve original sealed/generated bytes; owned prose remains checked.','batch/** -whitespace -text','original-blocked-diagnostic/** -whitespace -text','admitted-diagnostic/** -whitespace -text','executing-storage/** -whitespace -text','preflight/**/*.log -whitespace -text','*.dll binary','*.dylib binary'];raw=[]
for p in sorted(C.rglob('*')):
 if not p.is_file() or p.is_relative_to(C/'batch'):continue
 n=str(p.relative_to(C))
 if n in opaque:continue
 if p.is_relative_to(C/'source-snapshot') or p.is_relative_to(C/'preflight'):
  try:text=p.read_text()
  except UnicodeDecodeError:attrs.append('"'+n+'" binary');continue
  if any(line.endswith((' ','\t')) for line in text.splitlines()) or text.endswith('\n\n'):
   live=P/p.relative_to(C/'preflight') if p.is_relative_to(C/'preflight') else None
   assert live is None or sha(live)==sha(p);raw.append({'path':n,'sha256':sha(p),'liveCopyMatches':True});attrs.append('"'+n+'" -whitespace -text')
attrs.extend('"'+n+'" binary -whitespace' for n in opaque);(C/'.gitattributes').write_text('\n'.join(attrs)+'\n');(C/'RAW_WHITESPACE_BINDINGS.json').write_text(json.dumps({'exactCapturedFiles':raw,'opaqueParts':opaque,'ownedProseChecked':True},indent=2)+'\n')
jsoncount=0
for p in C.rglob('*.json'):json.loads(p.read_text());jsoncount+=1
for p in C.rglob('*'):
 if p.is_file():assert p.stat().st_size<100*1024*1024
(C/'PUBLICATION_CHECKS.json').write_text(json.dumps({'checkedUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'sourceCommit':PIN,'state':'Passed','jsonFiles':jsoncount,'localLinks':links,'sourceSnapshotsMatchGit':True,'transportPartsAndLiveHashesMatch':True,'rawEvidenceUnchanged':True,'modificationScope':docs+[rel],'acceptanceFlagsStillFalse':True},indent=2)+'\n')
m=C/'MANIFEST.sha256';m.write_text('\n'.join(sha(p)+'  '+str(p.relative_to(C)) for p in sorted(C.rglob('*')) if p.is_file() and p!=m)+'\n');git('diff','--check');git('add','--',*docs,rel);git('add','-f','--',*[str(p.relative_to(D)) for p in C.rglob('*') if p.is_file()]);git('diff','--cached','--check');expected=set(docs+[str(p.relative_to(D)) for p in C.rglob('*') if p.is_file()]);assert set(git('diff','--cached','--name-only').decode().splitlines())==expected
for n in expected:assert git('show',':'+n)==(D/n).read_bytes()
(P/'STAGING_RECEIPT.json').write_text(json.dumps({'checkedUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'stagedFiles':len(expected),'manifestSha256':sha(m),'state':'Passed','diffCheck':'Passed','exactStagedBytesMatch':True},indent=2)+'\n');print('Owned files staged and byte-verified',len(expected),flush=True)
