using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using UnityEngine;

namespace AssemblyShadowDemo
{
    /// <summary>
    /// Dedicated opt-in Player probe for the generated H1 FixedAssemblyBytes guard.
    /// It runs only when -shadowH1WitnessGuardProbeResult is present and never
    /// performs the positive ordinary load, which remains covered by fresh count runs.
    /// </summary>
    public static class H1WitnessGuardRuntimeProbe
    {
        private const string SiteId = "h1-count-ordinary-witness-image";
        private const string Prefix = "__AssemblyShadowReflectionBinding_";
        private const string ImageRelative = "AssemblyShadow/M00/AssemblyShadowBaseline.HotUpdate.dll.bytes";
        private const string ImageSha = "9108a2396fd1a292a1446a96b6e61ac19108fd930d8d2b70edb4c3af72780e27";

        [Serializable]
        public sealed class Result
        {
            public int schemaVersion = 1;
            public string kind = "H1WitnessGuardRuntimeProbe";
            public string result = "Failed", error = "";
            public bool il2cpp;
            public string unityVersion, platform, buildGuid;
            public string configurationSha256, configurationHash, guardName, imageSha256;
            public bool tamperRejected, nullRejected, callerBytesUnchanged;
            public int assemblyResolveEvents;
            public bool diagnosticOnly = true, humanGatePassed = false, mayEnterR02 = false;
        }

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
        private static void MaybeRun()
        {
            string output = Argument("-shadowH1WitnessGuardProbeResult");
            if (string.IsNullOrEmpty(output)) return;
            var result = new Result {
#if ENABLE_IL2CPP && !UNITY_EDITOR
                il2cpp = true,
#endif
                unityVersion = Application.unityVersion, platform = Application.platform.ToString(), buildGuid = Application.buildGUID,
            };
            try { Run(result); result.result = "Passed"; }
            catch (Exception error) { result.error = error.ToString(); Debug.LogException(error); }
            try
            {
                output = Path.GetFullPath(output);
                if (File.Exists(output) || Directory.Exists(output) || !Directory.Exists(Path.GetDirectoryName(output)))
                    throw new InvalidOperationException("Witness guard result must be a new file below an existing directory.");
                File.WriteAllText(output, JsonUtility.ToJson(result, true), new UTF8Encoding(false));
            }
            catch (Exception error) { Debug.LogException(error); Application.Quit(2); return; }
            Application.Quit(result.result == "Passed" ? 0 : 1);
        }

        private static void Run(Result result)
        {
            Require(result.il2cpp, "Witness guard acceptance requires an IL2CPP Player.");
            string configPath = Path.Combine(Application.streamingAssetsPath, "AssemblyShadow/M02/reflection-bindings.json");
            byte[] configBytes = File.ReadAllBytes(configPath);
            result.configurationSha256 = Hash(configBytes);
            string text = new UTF8Encoding(false).GetString(configBytes);
            Require(text.Contains("\"id\": \"" + SiteId + "\"") || text.Contains("\"id\":\"" + SiteId + "\""),
                "Staged configuration does not declare the H1 witness site.");
            MethodInfo[] guards = typeof(H1CountEarlyStartup).GetMethods(BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.DeclaredOnly)
                .Where(method => method.Name.StartsWith(Prefix, StringComparison.Ordinal) && method.ReturnType == typeof(Assembly) &&
                    method.GetParameters().Length == 1 && method.GetParameters()[0].ParameterType == typeof(byte[])).ToArray();
            Require(guards.Length == 1, "Expected exactly one generated byte-load guard on H1CountEarlyStartup.");
            MethodInfo guard = guards[0]; result.guardName = guard.Name;
            Require(guard.Name.Length == Prefix.Length + 129, "Generated witness guard identity has an unexpected length.");
            result.configurationHash = guard.Name.Substring(Prefix.Length, 64);
            string expectedSuffix = "_" + Hash(Encoding.UTF8.GetBytes(SiteId));
            Require(guard.Name.EndsWith(expectedSuffix, StringComparison.Ordinal), "Generated witness guard does not identify the declared site.");
            byte[] image = File.ReadAllBytes(Path.Combine(Application.streamingAssetsPath, ImageRelative));
            result.imageSha256 = Hash(image); Require(result.imageSha256 == ImageSha, "Pinned ordinary witness bytes differ.");
            byte[] altered = (byte[])image.Clone(); altered[altered.Length / 2] ^= 1; string alteredHash = Hash(altered);
            int resolverEvents = 0; ResolveEventHandler observer = (sender, args) => { ++resolverEvents; return null; };
            AppDomain.CurrentDomain.AssemblyResolve += observer;
            try
            {
                result.tamperRejected = Denied(guard, altered, result.configurationHash);
                result.nullRejected = Denied(guard, null, result.configurationHash);
                result.callerBytesUnchanged = Hash(image) == ImageSha && Hash(altered) == alteredHash;
                result.assemblyResolveEvents = resolverEvents;
            }
            finally { AppDomain.CurrentDomain.AssemblyResolve -= observer; }
            Require(result.tamperRejected && result.nullRejected && result.callerBytesUnchanged && result.assemblyResolveEvents == 0,
                "Generated witness guard did not reject before resolution or mutated caller bytes.");
        }

        private static bool Denied(MethodInfo guard, byte[] value, string configurationHash)
        {
            Exception failure = null;
            try { guard.Invoke(null, new object[] { value }); }
            catch (TargetInvocationException error) { failure = error.InnerException; }
            catch (Exception error) { failure = error; }
            return failure is InvalidOperationException && failure.Message ==
                "AssemblyShadow reflection denied; configuration=" + configurationHash + "; site=" + SiteId;
        }

        private static string Argument(string name)
        {
            string[] args = Environment.GetCommandLineArgs(); string result = null;
            for (int i = 0; i < args.Length; ++i) if (args[i] == name)
            { if (result != null || i + 1 >= args.Length) throw new InvalidOperationException("Missing/duplicate " + name); result = args[++i]; }
            return result;
        }

        private static string Hash(byte[] bytes)
        {
            using (SHA256 sha = SHA256.Create())
            { var b = new StringBuilder(64); foreach (byte value in sha.ComputeHash(bytes)) b.Append(value.ToString("x2")); return b.ToString(); }
        }
        private static void Require(bool value, string message) { if (!value) throw new InvalidOperationException(message); }
    }
}
